merge downstream changes for signup and import
ortelius/ortelius pull request #179
Opened 2020-12-07 23:32 UTC by sbtaylor15

2020-12-07 23:40 UTC, markyjackson-taulia requested changes
See inline comments

2020-12-07 23:40 UTC, markyjackson-taulia commented on chart/ms-ui/templates/deployment.yaml
> +---
Non-blocking nit: Can we add a line feed

2020-12-07 23:40 UTC, markyjackson-taulia commented on chart/ms-ui/templates/service.yaml
> +
Non-blocking nit: Can we add a line feed

2020-12-07 23:40 UTC, markyjackson-taulia commented on cloudbuild/cloudbuild-general.yaml
> +
Non-blocking nit: Can we add a line feed

2020-12-07 23:40 UTC, markyjackson-taulia commented on cloudbuild/cloudbuild-nginx.yaml
> +
Non-blocking nit: Can we add a line feed

2020-12-07 23:40 UTC, markyjackson-taulia commented on cloudbuild/cloudbuild-ui.yaml
> +
Non-blocking nit: Can we add a line feed

2020-12-07 23:40 UTC, markyjackson-taulia commented on cloudbuild/cloudbuild.toml
> +    CustomAction = "GLOBAL.HelmChart"
Non-blocking nit: Can we add a line feed

2020-12-07 23:40 UTC, markyjackson-taulia commented on cloudbuild/cloudbuild.yaml
> +
Non-blocking nit: Can we add a line feed

2020-12-07 23:40 UTC, markyjackson-taulia commented on docker/Dockerfile
> +COPY --from=0 /workspace/installers/linux/webadmin/webapp-runner.jar webadmin/webapp-runner.jar
COPY --from should reference a previously defined FROM alias?

2020-12-07 23:40 UTC, markyjackson-taulia commented on docker/Dockerfile
> +FROM quay.io/openmake/meister:latest
Using latest is prone to errors if the image will ever update. Pin the version explicitly to a release tag

2020-12-07 23:40 UTC, markyjackson-taulia commented on docker/entrypoint.sh
>  #!/bin/sh
On line 40:
^The mentioned syntax error was in this if expression.
    ^Couldn't parse this test expression. Fix to allow more checks.
         Expected this to be an argument to the unary condition.
                                ^You need a space before the ].
                                ^Missing space before ]. Fix any mentioned problems and try again.

2020-12-08 21:58 UTC, sbtaylor15 commented
Made changes per comments.  Please review again.

2020-12-08 21:58 UTC, markyjackson-taulia approved these changes
/lgtm

2020-12-08 22:05 UTC, sbtaylor15 commented
Missed one FROM alias.

2020-12-08 22:05 UTC, markyjackson-taulia approved these changes

2020-12-08 22:16 UTC, sbtaylor15 commented
Merging downstream maintenance changes, cloudbuild and dockerfile updates, API import updates and saas signup

2020-12-08 22:17 UTC, merged