Added a procedure meant for installing helm plugins
ortelius/ortelius pull request #335
Opened 2021-07-16 19:45 UTC by hatati

Sometimes applications can rely on different helm plugin in order to perform their deployment. The helm 'secrets' plugin for example (https://github.com/jkroepke/helm-secrets) can be used to decrypt a values.yaml that contains sensitive data at deploy time. Helm doesn't have that capability by itself. This procedure enables users to add a desired helm plugin with its corresponding version to the ortelius container.

2021-07-16 20:59 UTC, hatati commented
Currently im not able to sign the CLA. I keep getting redirected back to my other merged pull request when I finish signing through the EasyCLA.

2021-07-17 01:32 UTC, markyjackson-taulia requested changes
Hmm, can you ensure you signed as a member?

2021-07-17 14:13 UTC, sbtaylor15 commented
> Currently im not able to sign the CLA. I keep getting redirected back to my other merged pull request when I finish signing through the EasyCLA.

Looks like the email address and username assigned to the commit does not match the userid for the PR.  Check the config email and username on your local repo.  Then create a new local commit and push -f to GitHub.  This should sync the email and username that the PR has been created for.  Basically there is a mismatch between the PR and the commit.

2021-08-08 14:21 UTC, markyjackson-taulia requested changes
Kindly sign the easyla

2021-08-08 14:21 UTC, hatati commented
The git config in my local repo contained my work mail instead of my github mail. I corrected the config and created a new commit #d14aeab

2021-08-08 14:31 UTC, hatati commented
I still get the same issue when I try to sign the easycla

https://user-images.githubusercontent.com/8775749/128635556-00bcb8af-5a94-4e4b-8c43-b1aa31098967.mp4

2021-08-08 17:27 UTC, hatati commented
Did some git reset and got rid of the bad commit id

2021-08-08 17:34 UTC, markyjackson-taulia approved these changes

2021-08-08 17:34 UTC, merged